sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: XwTQrNwBko+ZV9TsERFNS+dkuZ4I+RgPp21E1IvkU+Eps1t/DoDM6rtOtNjfrc6NZWLcThRR1ZJoMyvVXnEuPlKK3/QJGHNUVoYDK/12vcKHuCdy0/DcLyqLLt2AU+InHYjpOK/EUlgfKgWZ0ZIU7ya3xpHcOM91aw7HkC8wRZ5W1z9v9wLbI1nC5HiEBPiKKqXyKDTZZL2kjbSyOluF9a7YKfKAhUZnHhJVeAg7bVstblW+kaNcjq1v+qyTJFP26llOsWDXIKcttrWjpSiB+O1uXTW4bAYpxOcS1jnwk1MjmXHN2vyau4FKnBya3s52+TP5Ath71v6eec4YyAhkjgMPRN4UIE9tJR3lvISaNPHd3pUDXVZ50X2+OTkoDCIYW8zgkGFFDhVtd/EhFZu/7zg3YSJ6pPMIRWhFUykETk3thUcH3Np+32iJ//MAm8eD/JAw1fsh9BfpGZDEdm3sjK4T57Ezn5lgPm+8C/LidJHVoIeYLiQjKrQHcTNd6GtNk9DLUobGbxSNmlE75XDPt+ui1CloHu725R14igHyBpjk40F9eHQ7GmI/YN28DyAR5sTc7luhYdL30SrjmkRgXVo0c4HviHbwcV46IF4YQ/qDVby0dp81Lzz6sDaFFG+NnfUyyiKa5YSWpI91o8vKJziP2yiEvkreVCa8JFu2STA=
    - secure: ZBhaqNK6T2YFPa1aNi6jbxw5cwy6Qrg+wZJGDqkIIqiy8VhBvOq5dKzSNUCty1oC+H0FveS509FSqXxCw2tEyIUBXB1iF+Z4ZUDyTmbfg9xlN6YpBruYJ3mfdFzxt9Q5rEnHTqYv7O9SRLdUbVnyWNQhblt5mkiSkBLT9uySP10BVRK/08CyxATiIZFHBcQUKhqI4h2CANuXljb0+HOpvkVCEN6Og9mcwPZ/Zx1EbE4kEM+uKLAgZkxtG73Fsu7z13OvfKDObPZOGvm+5MwrWi9IBWV9bLvd3xVUffiyPram+VIEild2JkCz4aLn2mEfbcShipcdfYb2xza8eOm7P/7PcEc+oVHNzC82tafexS+b9S/6RNNcEE5KO4hvVfwnM2eDdCC1bXGp+njSWFPlSwVL5+uKAklnzp9C5BQO4uFsY0/tM4nCn/rrE2k6lj+yLsb/CQCKDLUUbSdPImtKchSEite3NwP391/xRBAZuBIT8huQy7Zy9vQ/SSa59Xa90K2lzowExAymmznT43njQZ5edX+afT2tCcJUw/VQQWVQjI9WKbXMahJ6NhdFYJ51Ks4gzOCEPSDvTxIkfovjV1g5HD4nBAw420c2kCE+AjCZ9sYA3ItLf2pEEmtFOubACgEohscTUcS03fpNToExFCR93GrbDy6XW39h0Ku+VT8=
